"""
Email Service - Send notifications via SMTP
"""
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import aiosmtplib

from app.config import settings

logger = logging.getLogger(__name__)


class EmailService:
    """Service for sending email notifications"""

    @staticmethod
    async def send_job_completion_email(
        job_id: str,
        job_type: str,
        recipient_email: str,
        download_url: str,
        insight_url: str,
        total_documents: int,
        status: str = "completed"
    ) -> bool:
        """
        Send job completion notification email.

        Args:
            job_id: Job UUID
            job_type: Type of job (tar_processing/pdf_splitting)
            recipient_email: Recipient email address
            download_url: URL to download result archive
            insight_url: URL to download insight XML
            total_documents: Number of documents processed
            status: Job status (completed/failed)

        Returns:
            True if email sent successfully
        """
        if not settings.smtp_username or not settings.smtp_password:
            logger.warning("SMTP not configured, skipping email")
            return False

        try:
            # Build email
            message = MIMEMultipart("alternative")
            message["Subject"] = f"LudwigOne - Job {status.upper()}: {job_id}"
            message["From"] = settings.smtp_username
            message["To"] = recipient_email

            # Plain text version
            text_content = f"""
LudwigOne Document Processing

Job ID: {job_id}
Job Type: {job_type}
Status: {status.upper()}
Documents Processed: {total_documents}

Download Results: {download_url}
View Insight Report: {insight_url}

Thank you for using LudwigOne!
"""

            # HTML version
            html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
        .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
        .header {{ background: #4F46E5; color: white; padding: 20px; text-align: center; border-radius: 5px 5px 0 0; }}
        .content {{ background: #f9fafb; padding: 30px; border: 1px solid #e5e7eb; }}
        .status {{ font-size: 24px; font-weight: bold; color: {"#10B981" if status == "completed" else "#EF4444"}; margin: 20px 0; }}
        .info {{ background: white; padding: 15px; margin: 10px 0; border-radius: 5px; border-left: 4px solid #4F46E5; }}
        .info-label {{ font-weight: bold; color: #6B7280; }}
        .button {{ display: inline-block; background: #4F46E5; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; margin: 10px 5px; }}
        .button:hover {{ background: #4338CA; }}
        .footer {{ text-align: center; color: #6B7280; margin-top: 30px; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🎉 LudwigOne Document Processing</h1>
        </div>
        <div class="content">
            <div class="status">✅ {status.upper()}</div>

            <div class="info">
                <div><span class="info-label">Job ID:</span> {job_id}</div>
                <div><span class="info-label">Job Type:</span> {job_type.replace('_', ' ').title()}</div>
                <div><span class="info-label">Documents Processed:</span> {total_documents}</div>
            </div>

            <div style="text-align: center; margin: 30px 0;">
                <a href="{download_url}" class="button">📥 Download Results</a>
                <a href="{insight_url}" class="button">📊 View Insight Report</a>
            </div>

            <p style="color: #6B7280; text-align: center;">
                Your documents have been automatically categorized and organized.
            </p>
        </div>
        <div class="footer">
            <p>Generated by LudwigOne • Powered by AI</p>
        </div>
    </div>
</body>
</html>
"""

            # Attach parts
            part1 = MIMEText(text_content, "plain")
            part2 = MIMEText(html_content, "html")
            message.attach(part1)
            message.attach(part2)

            # Send email
            await aiosmtplib.send(
                message,
                hostname=settings.smtp_host,
                port=settings.smtp_port,
                username=settings.smtp_username,
                password=settings.smtp_password,
                start_tls=True  # Use STARTTLS for port 587
            )

            logger.info(f"Email sent successfully to {recipient_email}")
            return True

        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return False


# Global instance
email_service = EmailService()
